version: '3.7'

services:
  database:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: locbn123
      POSTGRES_USER: postgres
    ports:
      - 5435:5432
    network_mode: 'host'
