version: '3.7'

services:
  api:
    container_name: nestjs
    build:
      context: .
      dockerfile: Dockerfile.second
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5001:3333
    restart: always
    env_file: .env.dev
